name: CodeQL
on:
  push:
    branches: ["6.0", "5.0"]
  pull_request:

permissions:
    contents: read
    security-events: write

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['java-kotlin', 'javascript-typescript', 'python', 'actions']

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: github/codeql-action/init@e58424170fb0262c8d7ed60a2e84b9bffe205c67 # v2.26.1
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/autobuild@e58424170fb0262c8d7ed60a2e84b9bffe205c67 # v2.26.1
      - uses: github/codeql-action/analyze@e58424170fb0262c8d7ed60a2e84b9bffe205c67 # v2.26.1
